### ISSUE TITLE
Missing API functionality

### ISSUE THREAD

**Issue by PublicGameCoder** [PikaMug/LocaleLib#3]
I think this API is missing the ability to obtain the item name by material and damage value.

It consist the ability to get the item by material.
```JAVA
String itemName = localeManager.queryMaterial(material);
```
But I'd also like to add a damage value to get what type of the material to use.
```JAVA
String itemName = localeManager.queryMaterial(material, (short) 5);
```
Or even make it obtainable through the player:
```JAVA
String playerLangItemName = localeManager.queryMaterial(player, material, (short) 5);
```

**Comment by PublicGameCoder** [comment]
I think this is only possible for english.
But to obtain the english translation is still a big goal.

**Comment by PikaMug** [comment]
Thanks for the input, but I'm afraid it's missing because it's impossible afaik. The LocaleQuery class merely converts a Material into a key, which is then sent to the client for translation. For more information, visit https://www.spigotmc.org/resources/localelib.65617/

If you aware of a way to retrieve the translated string back from the client, PRs are welcome.

**Comment by PublicGameCoder** [comment]
I will add a PR on how it can retrieve the item name from the key from the server's locale
